/* eslint-disable no-console */
import { showLogger } from '@/utils/env'

/**
 * A console logger function that only logs in development env.
 * @param object - The object to log
 * @param comment - Autogenerated with `lg` snippet
 */
export const logger = (object: unknown, comment?: string): void => {
  if (!showLogger) return

  console.log(
    '%c ============== INFO LOG \n',
    'color: #22D3EE',
    `${typeof window !== 'undefined' && window?.location.pathname}\n`,
    `=== ${comment ?? ''}\n`,
    object,
  )
}
